# Site settings
title: GPDB Rocks!
email: yyao@pivotal.io
description: > # this means to ignore newlines until "baseurl:"
  Everything about GPDB
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://gpdb.rocks" # the base hostname & protocol for your site
twitter_username: yydzero
github_username:  yydzero

# Build settings
markdown: kramdown
