# Site settings
title: Greenplum QQ 交流群：99194625
description: > # this means to ignore newlines until "baseurl:"
  Everything about GPDB
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://greenplum.cn" # the base hostname & protocol for your site

# Build settings
markdown: kramdown
